version: '3'

services:

  backend:
    #container_name: price-service_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JMS_PORT=61616
      - JMS_HOST=docker.for.mac.localhost
      - JMS_USER=admin
      - JMS_PASS=admin
      - JMS_RESOURCE_ADAPTER_NAME=activemq-rar-5.15.9
      - GROUP_QUEUE=groups
    ports:
      - "8081:8080"
      - "9081:9009"
      - "4881:4848"
    restart: always
    entrypoint:
      - java
      - -Xdebug
      - -Xrunjdwp:transport=dt_socket,address=*:9009,server=y,suspend=n
      - -jar
      - /opt/payara/payara-micro.jar
    command: ["--deploy", "/opt/payara/activemq-rar-5.15.9.rar", "--postdeploycommandfile", "/opt/payara/deployments/postdeploy.txt"]
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
